- .github/workflows/deploy-docs.yml
- .github/workflows/test.yml
- README.md
- Adds Node.js lts/iron to test matrix; Node.js 20 is now offcially supported.
- Updates GitHub Actions
> feat: adds Node.js lts/iron to test matrix

- src/lib/services/auth/__tests__/identities.spec.ts
- src/lib/services/auth/config.ts
- src/lib/services/auth/index.ts
- src/lib/services/auth/service/identities.ts
- Adds support for fetching a single identity (by UUID) and list – https://docs.globus.org/api/auth/reference/#identities_api
> feat(Globus Auth): adds support for the Identities resources in the Globus Auth API

- src/lib/services/flows/service/flows.ts
- `.destory` is a legacy naming scheme, we use `remove` instead (see https://globus.github.io/globus-sdk-javascript/modules/_globus_sdk.html#md:service-method-names)
- Adds temporary alias for `destory` to `remove` to avoid breaking change.
> fix(Flows): flows.destory has been replaced by flows.remove

- src/lib/services/transfer/__tests__/__snapshots__/endpoint.spec.ts.snap
- src/lib/services/transfer/__tests__/__snapshots__/task.spec.ts.snap
- src/lib/services/transfer/__tests__/endpoint.spec.ts
- src/lib/services/transfer/__tests__/task.spec.ts
- src/lib/services/transfer/config.ts
- src/lib/services/transfer/index.ts
- src/lib/services/transfer/service/endpoint-search.ts
- src/lib/services/transfer/service/endpoint.ts
- src/lib/services/transfer/service/file-operations.ts
- src/lib/services/transfer/service/task-submission.ts
- src/lib/services/transfer/service/task.ts
- src/lib/services/transfer/types.ts
- feat(Transfer): adds support for `transfer.task.*` service methods, including: `getAll`, `get`, `update`, `cancel`, `remove`, `getEventList`, `getSuccessfulTransfers`, `getSkippedErrors`, and `getPauseInfo`
- feat(Transfer): adds support for `endpoint.remove`
- chore(Transfer): Adds Typescript types for `Transfer['Paging']`
> feat(Transfer): adds Task-related service methods, endpoint.remove, and updates to shared scope constant.

- src/lib/services/flows/service/flows.ts
> chore(Flows)!: Removes `flows.destroy` alias, replaced by `flows.remove` in 1.15.0

- src/__mocks__/handlers.ts
- src/lib/services/auth/__tests__/__snapshots__/oauth2.spec.ts.snap
- src/lib/services/auth/__tests__/oauth2.spec.ts
- src/lib/services/auth/service/oauth2/token.ts
- src/lib/services/shared.ts
- updates invalid resource path (oauth => oauth2)
- cleans up the raw `body` handling in the serviceRequest handler.
- adds `formData` testing to the mirror test utility
> fix(Auth): addresses an issue causing auth.oauth2 methods from making proper requests.

- src/lib/services/transfer/types.ts
This didn't seem to cause any compile time or runtime issues (since we allow arbitrary payloads), but updating for correctness.
> fix(Typescript, Transfer): fix improper DATA_TYPE type references for transfer.fileOperations.mkdir and transfer.fileOperations.rename

- src/lib/services/search/service/query.ts
- src/lib/services/transfer/types.ts
We now have
https://github.com/globus/globus-sdk-javascript/blob/main/src/lib/core/url.ts to handle building search strings. The query objects should accept the types as described in our service documentation.
> fix(Typescript): allow non-string types for query properties

- src/lib/services/globus-connect-server/__tests__/client.spec.ts
- src/lib/services/globus-connect-server/client.ts
- We added a few methods in a previous release that were not exposed via the `getClient` method.
- Adds a test to ensure service resources and methods are present on the `getClient` export.
> fix(GCS): ensure all Globus Connect Server service resource methods are available on `getClient`

- src/lib/services/transfer/service/endpoint-manager/task.ts
These were previously using the single document type as the response, when it is actually a list response.
> fix(Typescript, Endpoint Manager, Transfer): updates the types returned by endpointManager.task.getSuccessfulTransfers and getSkippedErrors

- package-lock.json
- package.json
- src/index.ts
- src/lib/core/global.ts
- src/lib/services/compute/__tests__/__snapshots__/compute.spec.ts.snap
- src/lib/services/compute/__tests__/compute.spec.ts
- src/lib/services/compute/config.ts
- src/lib/services/compute/index.ts
- src/lib/services/compute/service/endpoints.ts
- Adds `compute.endpoints.get` and `compute.endpoints.getAll`
- Bumps @globus/types requirement to latest (0.0.7)
> feat(Compute): adds initial support for Globus Compute

- src/lib/services/transfer/types.ts
- src/lib/services/types.ts
This also drops the `Extract`s from the "Editable" unions, as they aren't adding any type safety.
> fix(Types): adds missing endpoint record fields

- src/lib/services/globus-connect-server/constants.ts
- Includes "Quantum" in the display name, previously only "ActiveScale"
> chore(Connectors): updates "Quantum ActiveScale" `DISPLAY_NAME` property

- tsconfig.package.json
- For those looking to reduce bundle size (or using TS), we recommend using the ESM build instead of the CJS build.
> fix: disable importHelpers to avoid peerDependency of tslib for consumers

- src/lib/core/authorization/AuthorizationManager.ts
- src/lib/core/authorization/index.ts
- src/lib/core/errors.ts
The `basic` example README was also updated in a previous commit ([d111aae](https://github.com/globus/globus-sdk-javascript/commit/d111aaed2956275e160aad8b9ff5fb8e4b6dd4a0)).
closes #172
> docs: adds additional documentation to Authorization and Errors

- README.md
The Typedoc generated (and GitHub Pages hosted) version of the documentation provides an invalid link when relative path is used.
closes #179
> docs: use absolute URL for "Examples" link

- src/lib/services/transfer/service/endpoint-manager/task.ts
https://docs.globus.org/api/transfer/advanced_collection_management/#get_task_pause_info
> fix(Transfer, Typescript): updates return type of `transfer.endpointManager.getPauseInfo` (PauseInfoLimitedDocument)

- src/lib/core/__tests__/errors.spec.ts
- src/lib/core/authorization/AuthorizationManager.ts
- src/lib/core/errors.ts
- src/lib/services/auth/index.ts
- adds `prompt` and `required_scopes` to `AuthorizationRequirementsError`
- all members of `AuthorizationRequirementsError` are optional.
- adds `AuthorizationQueryParameters` type for the Globus Auth query parameters... which are different!
- adds `sdk.errors.toAuthoriztionQueryParams` utility.
- updates `AuthorizationManager` to use the new utility.
> fix(Authorization): improves AuthorizationRequirementsError type and related utilities.

- src/lib/core/errors.ts
Missed this addition in #206 (only added to the query parameter type).
> fix(errors, Typescript): adds `session_required_policies` to `AuthorizatonRequirementsError` type

- src/__mocks__/errors/authorization_parameters.ts
- src/lib/core/__tests__/authorization/AuthorizationManager.spec.ts
- src/lib/core/__tests__/errors.spec.ts
- src/lib/core/errors.ts
- This better reflects the current state of `authorization_parameters` returned by services.
- Eventually, this will be updated to require/introspect `code`, but until most services are using the SDK to generate these errors the presence of `code` in the response will likely be hit or miss.
> fix(Errors): updates isAuthorizationRequirementsError method to not require "message" or "code"

- src/lib/core/__tests__/global.spec.ts
- src/lib/core/global.ts
- precedence should have the ENV var above config object
> fix: `GLOBUS_SDK_ENVIRONMENT` environment variable will now take precedence over `GLOBUS_SDK_OPTIONS`

- src/lib/core/__tests__/authorization/AuthorizationManager.spec.ts
- src/lib/core/authorization/AuthorizationManager.ts
- The `AutorizationManager` will now only automatically attempt to refresh tokens on creation when configured with `automaticSilentRefresh: true`.
- The `startSilentRefresh` internal method has also been updated dispatch an `authenticated` event after processing all refresh tokens.
- A new property `manager.waitForSilentRefresh` exposes a Promise depicting the state of _all_ inflight refresh requests.
All of these changes are in service of better application state control on instance creation. Without these changes, it was fairly common for any application listening to changes to tokens to effectively bootstrap twice - once for the token in storage and again when the tokens were refreshed.
> fix(Authorization): Automatic silent refresh of tokens (on instantiation) is now controlled via configuration (disabled by default).

- src/lib/services/transfer/__tests__/utils.spec.ts
- src/lib/services/transfer/index.ts
- src/lib/services/transfer/utils.ts
feat: adds `transfer.utils.readableBytes()`
- This is used in the portals and Globus Web Application for rendering file sizes.
feat: adds `transfer.utils.isDirectory()` and `transfer.utils.isFileDocument()`
- Used in the portals and Globus Web Application for determining more specific types from `Globus.Transfer.FileDocument`
> feat: adds Transfer utilities related to `FileDocument`

- src/lib/services/search/__tests__/__snapshots__/index.spec.ts.snap
- src/lib/services/search/__tests__/index.spec.ts
- src/lib/services/search/__tests__/query.spec.ts
- src/lib/services/search/index.ts
- src/lib/services/search/service/query.ts
- src/lib/services/search/service/search-index.ts
- src/lib/services/search/types.ts
feat(Search, Typescript): Moves most Globus Search types internal to the SDK (previously sourced from `@globus/types`)
> feat(Search): Adds methods for interacting and management of Globus Search indicies via (e.g. `search.index.create()`, `search.index.ingest()`)

- package-lock.json
- package.json
- src/core/__tests__/authorization/AuthorizationManager.spec.ts
- src/core/__tests__/authorization/RedirectTransport.spec.ts
- src/core/authorization/AuthorizationManager.ts
- src/core/authorization/RedirectTransport.ts
- src/core/authorization/pkce.ts
- src/core/url.ts
- src/services/auth/__tests__/__snapshots__/oauth2.spec.ts.snap
- src/services/auth/__tests__/oauth2.spec.ts
- src/services/auth/service/oauth2/token.ts
The js-pkce package has presented a few problems for our usage:
1. It is currently bundled to CommonJS _and_ uses a default export, which causes issues with our ESM build.
2. The code is transpiled to ES5, which is outdated for our target support.
3. There are many outdated dependencies; It's use of crypto-js stands out the most, since `crypto` and `crypto.webcrypto` are native in most modern browsers and Node runtimes.
This PR drops the js-pkce package and updates our implementation of PKCE to use native methods where possible.
> fix(Authorization): updates PKCE integration to use native API (drops js-pkce package)

- src/core/__tests__/authorization/AuthorizationManager.spec.ts
- src/core/__tests__/authorization/TokenLookup.spec.ts
- src/core/authorization/AuthorizationManager.ts
- src/core/authorization/TokenLookup.ts
- src/services/auth/types.ts
feat: Adds `prompt` method to `AuthorizationManager` - allows prompting for consent **without** reseting configured authorization context.
feat: Tokens managed by an `AuthorizationManager` will now be stored as a `StoredToken` type, which will include a `__metadata` property in addition to the raw `Token`. The `__metadata` will contain information about the creation and expiration time of the token allowing for improved refresh functionality.
feat: Adds `isTokenExpired` method for determining whether or not a stored token is expired.
> feat(Authorization): `AuthorizationManager` enhancements.

- src/core/__tests__/authorization/RedirectTransport.spec.ts
- src/core/authorization/RedirectTransport.ts
This will ensure the value in sessionStorage represents the caller-provided value.
Relates to #318
> fix(Authorization): ensure caller-provided "state" is stored on OAuth dispatch

- src/core/__tests__/errors.spec.ts
- src/core/errors.ts
This addresses situations where `AuthorizationManager.handleAuthorizationError` or `.handleError` was being used and not requesting the proper scopes by default.
> fix(Authorization): The value of the 'required_scopes' property of an AuthorizationError is now sent to Globus Auth as 'scope' parameter by default.

- src/services/search/service/search-index.ts
- https://github.com/globusonline/globus-search/pull/1528/files
> chore(Search, Typescript): Updates return type of `index.get` to `IndexWithPermissions` type.

- src/services/auth/__tests__/identities.spec.ts
- src/services/auth/index.ts
- src/services/auth/service/identities/consents.ts
- src/services/auth/service/identities/index.ts
chore(Auth): Updates the `auth.identities` direct import path to `@globus/sdk/services/auth/identities/index.js`
chore(Auth, Typescript): adds `Consent` type.
> feat(Auth): Adds `auth.identities.consents.getAll` service method.

- src/services/auth/__tests__/identities.spec.ts
- src/services/auth/service/identities/consents.ts
- src/services/auth/service/identities/index.ts
This error in the path sort of propagated to all of the Globus Auth identity methods... they should be prefixed with `/v2/api/` (https://docs.globus.org/api/auth/reference/#get_identity).
> fix(Auth): Ensure proper API paths for identity-related Globus Auth resources (e.g. GET /v2/api/identities)

- src/services/auth/__tests__/utils.spec.ts
- src/services/auth/index.ts
- src/services/auth/utils.ts
- Adds `ScopeTreeLeaf` type.
This method will take a scope string and convert it into an array of `ScopeTreeLeaf`s for processing.
```js
toScopeTree('urn:globus:auth:scope:transfer.api.globus.org:all');
```
```json
[
{
"scope": "urn:globus:auth:scope:transfer.api.globus.org:all",
"atomically_revocable": false,
"children": []
}
]
```
```js
toScopeTree('urn:globus:auth:scope:transfer.api.globus.org:all[*https://auth.globus.org/scopes/8062693f-f8c2-46be-86d0-de651a974ff3/data_access[https://auth.globus.org/scopes/8062693f-f8c2-46be-86d0-de651a974ff3/ls]] urn:globus:auth:scope:flows.api.globus.org:all');
```
```json
[
{
"scope": "urn:globus:auth:scope:transfer.api.globus.org:all",
"atomically_revocable": false,
"children": [
{
"scope": …
```
> feat(Auth): adds Globus Auth `utils`, including `auth.utils.hasConsentForScope`

- src/services/search/service/query.ts
This _seems_ like a more accurate representation of https://docs.globus.org/api/search/reference/post_query/#gfacet...
I was specifically encountering an issue with `size` not being allowed (optional) when using `type: "terms"`.
> fix(Typescript, Search): Improve the GFacet Search type

- src/__tests__/request.spec.ts
- src/index.ts
This PR exports our internal `serviceRequest` generator method as `request` as a way for consumers to compose requests to supported services that will use the same processing as "officially supported" methods.
For example, we are currently lacking many methods for https://timer.automate.globus.org/redoc#tag/jobs (sc-41746), which can now be expressed as:
```ts
import { request } from '@globus/sdk';
const jobs = await request({ service: 'COMPUTE', path: '/jobs' }, { headers: { Authorization: "..." }} );
```
To use an `AuthorizationManager` instance, its a little more involved...
```ts
import { request } from "@globus/sdk";
const jobs = await request(
{
service: "COMPUTE",
path: "/jobs",
resource_server: "524230d7-ea86-4a52-8312-86065a9e0417",
},
{},
{ authorization }
);
```
You can …
> feat: Adds `request` method for making generic service requests using similar signatures and authorization integration.

- .github/workflows/ci.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/release-please.yml
- .nvmrc
- README.md
- package-lock.json
- package.json
- lts/jod is considered the new default version for development and CI; Active LTS release.
> feat!: Drops support for Node.js 18

- src/core/__tests__/authorization/AuthorizationManager.spec.ts
- src/core/__tests__/authorization/RedirectTransport.spec.ts
- src/core/authorization/AuthorizationManager.ts
- src/core/authorization/PopupTransport.ts
- src/core/authorization/RedirectTransport.ts
- src/core/authorization/pkce.ts
This pull request introduces a new transport for the `AuthorizationManager` – the `PopTransport`.
This transport is intended to facilitate using `@globus/sdk` as an authorization mechanism when a redirect is not possible (e.g. when inside of an `<iframe>`).
`<MORE DOCUMENTATION TO FOLLOW>`
---
Attached is an example of the usage in an experimental Storybook.
https://github.com/user-attachments/assets/32680ef7-ef0e-43b4-a9aa-e973be94adc4
> feat(Authorization): adds experimental `PopupTransport` for AuthorizationManager
